export enum AppRole {
  KNOWLEDGESYSTEM_USER = "KNOWLEDGESYSTEM_USER",
  FACTSDASHBOARD_CEO = "FACTSDASHBOARD_CEO",
  KAFKAPROXY_USER = "KAFKAPROXY_USER",
  TASKJUNCTION_USER = "TASKJUNCTION_USER",
  INFOGRAPHICENGINE_ADMIN = "INFOGRAPHICENGINE_ADMIN",
  APPOINTMENTCENTER_USER = "APPOINTMENTCENTER_USER",
  KAFKAPROXY_ADMIN = "KAFKAPROXY_ADMIN",
  INFOGRAPHICENGINE_USER = "INFOGRAPHICENGINE_USER",
  USERMANAGERSYSTEM_USER = "USERMANAGERSYSTEM_USER",
  USERMANAGERSYSTEM_ADMIN = "USERMANAGERSYSTEM_ADMIN",
  TASKJUNCTION_ADMIN = "TASKJUNCTION_ADMIN",
  FACTMANAGER_ADMIN = "FACTMANAGER_ADMIN",
  BASEFORMDROOLSENGINE_USER = "BASEFORMDROOLSENGINE_USER",
  APPOINTMENTCENTER_ADMIN = "APPOINTMENTCENTER_ADMIN",
  BASEFORMDROOLSENGINE_ADMIN = "BASEFORMDROOLSENGINE_ADMIN",
  FACTMANAGER_USER = "FACTMANAGER_USER",
  KNOWLEDGESYSTEM_ADMIN = "KNOWLEDGESYSTEM_ADMIN"
}
